import "./globals.css";
import type { Metadata } from "next";
import {
  migra,
  PPNeueMachinaInktrap,
  PPNeueMachinaPlain,
} from "@/config/fonts";

export const metadata: Metadata = {
  title: "Plainthing Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${PPNeueMachinaPlain.variable} ${PPNeueMachinaInktrap.variable} ${migra.variable} font-plain`}
      >
        {/*<Background />*/}
        <div className="bg-[#1A181E] px-16">{children}</div>
      </body>
    </html>
  );
}
